"""
系统管理API，用于密钥生成和系统初始化
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.deps import get_db
from app.jwt_auth import AuthenticatedUser, require_jwt_token
from app.logging_config import logger
from app.services.key_management_service import (
    APIKeyGenerationError,
    generate_system_secret_key,
    initialize_system_admin,
    KeyManagementServiceError,
    rotate_system_secret_key,
    UserCreationError,
    validate_key_strength,
)

router = APIRouter(tags=["system"], prefix="/system")


# 请求和响应模型
class SecretKeyGenerationRequest(BaseModel):
    length: int = Field(default=64, ge=32, le=256, description="密钥长度")


class SecretKeyResponse(BaseModel):
    secret_key: str = Field(..., description="生成的系统密钥")


class SystemAdminInitRequest(BaseModel):
    username: str = Field(..., min_length=3, max_length=50, description="管理员用户名")
    email: str = Field(..., description="管理员邮箱")
    display_name: str = Field(default="System Administrator", description="管理员显示名称")


class SystemAdminInitResponse(BaseModel):
    username: str
    email: str
    password: str
    api_key: str


class KeyValidationRequest(BaseModel):
    key: str = Field(..., description="要验证的密钥")


class KeyValidationResponse(BaseModel):
    is_valid: bool = Field(..., description="密钥是否有效")
    message: str = Field(..., description="验证结果消息")


@router.post("/secret-key/generate", response_model=SecretKeyResponse)
def generate_secret_key(
    request: SecretKeyGenerationRequest,
    current_user: AuthenticatedUser = Depends(require_jwt_token),
) -> SecretKeyResponse:
    """
    生成系统主密钥
    
    Args:
        request: 密钥生成请求
        current_user: 当前认证用户
        
    Returns:
        生成的系统密钥
        
    Raises:
        HTTPException: 如果用户不是超级用户
    """
    if not current_user.is_superuser:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="只有超级管理员可以生成系统密钥",
        )
    
    try:
        secret_key = generate_system_secret_key(request.length)
        logger.warning(f"System secret key generated by superuser {current_user.username}")
        return SecretKeyResponse(secret_key=secret_key)
    except KeyManagementServiceError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate secret key: {str(exc)}",
        )


@router.post("/admin/init", response_model=SystemAdminInitResponse)
def init_system_admin(
    request: SystemAdminInitRequest,
    db: Session = Depends(get_db),
) -> SystemAdminInitResponse:
    """
    初始化系统管理员账户
    
    Args:
        request: 初始化请求
        db: 数据库会话
        
    Returns:
        管理员凭证
        
    Raises:
        HTTPException: 如果系统已有用户或初始化失败
    """
    try:
        admin_credentials = initialize_system_admin(
            session=db,
            username=request.username,
            email=request.email,
            display_name=request.display_name,
        )
        
        return SystemAdminInitResponse(
            username=admin_credentials["username"],
            email=admin_credentials["email"],
            password=admin_credentials["password"],
            api_key=admin_credentials["api_key"],
        )
    except KeyManagementServiceError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to initialize system admin: {str(exc)}",
        )


@router.post("/secret-key/rotate", response_model=SecretKeyResponse)
def rotate_secret_key(
    current_user: AuthenticatedUser = Depends(require_jwt_token),
) -> SecretKeyResponse:
    """
    轮换系统主密钥
    
    Warning: 这将使所有现有的密码哈希和API密钥失效！
    
    Args:
        current_user: 当前认证用户
        
    Returns:
        新生成的系统密钥
        
    Raises:
        HTTPException: 如果用户不是超级用户
    """
    if not current_user.is_superuser:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="只有超级管理员可以轮换系统密钥",
        )
    
    try:
        new_key = rotate_system_secret_key()
        logger.error(f"System secret key rotation initiated by superuser {current_user.username}")
        return SecretKeyResponse(secret_key=new_key)
    except KeyManagementServiceError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to rotate secret key: {str(exc)}",
        )


@router.post("/key/validate", response_model=KeyValidationResponse)
def validate_key(
    request: KeyValidationRequest,
) -> KeyValidationResponse:
    """
    验证密钥强度
    
    Args:
        request: 验证请求
        
    Returns:
        验证结果
    """
    is_valid = validate_key_strength(request.key)
    
    if is_valid:
        message = "密钥强度足够"
    else:
        message = "密钥强度不足，建议使用更长的随机密钥"
    
    return KeyValidationResponse(is_valid=is_valid, message=message)


@router.get("/status")
def get_system_status(
    current_user: AuthenticatedUser = Depends(require_jwt_token),
) -> dict:
    """
    获取系统状态
    
    Args:
        current_user: 当前认证用户
        
    Returns:
        系统状态信息
    """
    if not current_user.is_superuser:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="只有超级管理员可以查看系统状态",
        )
    
    # 这里可以添加更多的系统状态检查
    status_info = {
        "status": "healthy",
        "message": "系统运行正常",
    }
    
    return status_info


__all__ = ["router"]